# [Storage Configuration]
# Economy Options: MEMORY, MONGODB
# Rank Options: MEMORY, MONGODB
# Warp Options: MEMORY, MONGODB
# Cosmetics Options: JSON, MONGODB

storage.economy.type: MONGODB
storage.rank.type: MONGODB
storage.warp.type: MEMORY
storage.cosmetics.type: JSON

# MongoDB Settings
mongodb.uri:
mongodb.database: mcuniverse

# RedisDB Settings
redis.uri: