# [Storage Configuration]
# Economy Options: MEMORY, MONGODB
# Rank Options: MEMORY, MONGODB
# Warp Options: MEMORY, MONGODB
# Cosmetics Options: JSON, MONGODB

storage.economy.type: MONGODB
storage.rank.type: MONGODB
storage.warp.type: MEMORY
storage.cosmetics.type: JSON

# MongoDB Settings
mongodb.uri: mongodb+srv://gclogs:Muniverse0202!@cluster0.h7iurln.mongodb.net/
mongodb.database: mcuniverse

# RedisDB Settings
redis.uri: redis://default:sKPYYJViLuwaBGTkciioraCkqfx9vZZB@redis-19241.c16.us-east-1-3.ec2.cloud.redislabs.com:19241